# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  MIX_ENV: test
  PW_TIMEOUT: 4000

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup languages
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: mix do deps.get, deps.compile
      - name: Check Formatting
        run: mix format --check-formatted
      - name: Check Credo
        run: mix credo
      - name: Compiles without warnings
        run: mix compile --warnings-as-errors
      - name: Install JS dependencies, build assets and install browsers
        run: mix setup
      - name: Run tests
        run: "mix test --warnings-as-errors || if [[ $? = 2 ]]; then PW_TRACE=true mix test --failed; else false; fi"
      - name: Fail if screenshot on exit failed
        run: |
          if ! ls screenshots/PhoenixTest.Playwright.CaseTest.test__tag__screenshot_saves_screenshot_on_test_exit* >/dev/null 2>&1; then
            echo "Screenshot on exit feature failed"
            exit 1
          fi
      - name: Fail if trace on exit failed
        run: |
          if ! ls traces/PhoenixTest.Playwright.CaseTest.test__tag__trace_saves_trace_on_test_exit* >/dev/null 2>&1; then
            echo "Trace on exit feature failed"
            exit 1
          fi
      - name: Upload failure traces
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Traces
          path: ./traces
          if-no-files-found: ignore
      - name: Upload verification screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ./screenshots
          if-no-files-found: ignore
